---

- name: Install ntp
  apt:
    name: ntp
    update_cache: yes

- name: Edit config file
  template: 
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644

- name: Restart ntp
  service: 
    name: ntp
    state: restarted
