---

- name: Install ntp
  apt:
    name: ntp
    state: present

- name: Edit config file
  template: 
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart ntp
